### ISSUE TITLE
Support for CSS 4.x.x

### ISSUE THREAD

**Issue by smessie** [RubenVerborgh/solid-metadata-extender#2]
I'm trying to use this package together with CommunitySolidServer v4.0.1 but this package has not yet been updated to support CSS v4.x.x
Would such an update be possible to release?

**Comment by RubenVerborgh** [comment]
Not needed, this functionality is part of CSS now 😎
Need to update the README though.

**Comment by smessie** [comment]
Cool!
Does it requires additional configuration to the CSS to work or does it uses the same configuration as in config/example.json?

**Comment by RubenVerborgh** [comment]
The spec-required metadata is already included out of the box, so no config needed.
